import type { Metadata } from "next";

import "./styles/index.scss";

import { viewportConfig } from "$shared/config";
import { getUser, UserContextProvider } from "$entities/user";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export const viewport = viewportConfig;

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const user = await getUser();

	return (
		<html lang="ru">
			<UserContextProvider value={user}>
				<body>
					<main
						style={{
							alignItems: "center",
							justifyContent: "center",
							textAlign: "center",
						}}
					>
						<h3>{user?.name ?? "No login"}</h3>
						{children}
					</main>
				</body>
			</UserContextProvider>
		</html>
	);
}
