import type { Metadata } from "next";

import "./styles/index.scss";

import { viewportConfig } from "$shared/config";
import { getUser } from "$entities/user";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export const viewport = viewportConfig;

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const user = await getUser();

	return (
		<html lang="ru">
			<body>
				<main>
					<h1>{user?.name}</h1>
					{children}
				</main>
			</body>
		</html>
	);
}
