// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
	GetNewTokensData,
	GetNewTokensErrors,
	GetNewTokensResponses,
	LoginData,
	LoginErrors,
	LoginResponses,
	LogoutData,
	LogoutErrors,
	LogoutResponses,
	ProfileData,
	ProfileErrors,
	ProfileResponses,
	RegisterData,
	RegisterErrors,
	RegisterResponses,
	UpdateProfileData,
	UpdateProfileErrors,
	UpdateProfileResponses,
} from "./types.gen";

export type Options<
	TData extends TDataShape = TDataShape,
	ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
	/**
	 * You can provide a client instance returned by `createClient()` instead of
	 * individual options. This might be also useful if you want to implement a
	 * custom client.
	 */
	client?: Client;
	/**
	 * You can pass arbitrary values through the `meta` object. This can be
	 * used to access values that aren't defined as part of the SDK function.
	 */
	meta?: Record<string, unknown>;
};

export const profile = <ThrowOnError extends boolean = false>(
	options?: Options<ProfileData, ThrowOnError>
) =>
	(options?.client ?? client).get<
		ProfileResponses,
		ProfileErrors,
		ThrowOnError
	>({ url: "/user/profile", ...options });

export const updateProfile = <ThrowOnError extends boolean = false>(
	options: Options<UpdateProfileData, ThrowOnError>
) =>
	(options.client ?? client).put<
		UpdateProfileResponses,
		UpdateProfileErrors,
		ThrowOnError
	>({
		url: "/user/profile",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});

export const login = <ThrowOnError extends boolean = false>(
	options: Options<LoginData, ThrowOnError>
) =>
	(options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
		url: "/auth/login",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});

export const register = <ThrowOnError extends boolean = false>(
	options: Options<RegisterData, ThrowOnError>
) =>
	(options.client ?? client).post<
		RegisterResponses,
		RegisterErrors,
		ThrowOnError
	>({
		url: "/auth/register",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});

export const getNewTokens = <ThrowOnError extends boolean = false>(
	options?: Options<GetNewTokensData, ThrowOnError>
) =>
	(options?.client ?? client).post<
		GetNewTokensResponses,
		GetNewTokensErrors,
		ThrowOnError
	>({ url: "/auth/login/access-token", ...options });

export const logout = <ThrowOnError extends boolean = false>(
	options?: Options<LogoutData, ThrowOnError>
) =>
	(options?.client ?? client).post<LogoutResponses, LogoutErrors, ThrowOnError>(
		{ url: "/auth/logout", ...options }
	);
