// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
	baseUrl: string;
};

export type UserWithoutPassword = {
	id: string;
	createdAt: string;
	updatedAt: string;
	email: string;
	name?: string;
};

export type UserResponseDto = {
	user: UserWithoutPassword;
};

export type UnauthorizedErrorResponseDto = {
	statusCode: number;
	message: string;
	error: string;
};

export type NotFoundErrorResponseDto = {
	statusCode: number;
	message: string;
	error: string;
};

export type InternalServerErrorResponseDto = {
	statusCode: number;
	message: string;
	error: string;
};

export type UserDto = {
	email?: string;
	name?: string;
	password?: string;
};

export type UserUpdateResponseDto = {
	email: string;
	name?: string;
};

export type UnprocessableEntityErrorResponseDto = {
	statusCode: number;
	error: string;
	errors: {
		[key: string]: unknown;
	};
};

export type AuthDto = {
	email: string;
	password: string;
};

export type BadRequestErrorResponseDto = {
	statusCode: number;
	message: string;
	error: string;
};

export type ProfileData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/user/profile";
};

export type ProfileErrors = {
	401: UnauthorizedErrorResponseDto;
	404: NotFoundErrorResponseDto;
	500: InternalServerErrorResponseDto;
};

export type ProfileError = ProfileErrors[keyof ProfileErrors];

export type ProfileResponses = {
	200: UserResponseDto;
};

export type ProfileResponse = ProfileResponses[keyof ProfileResponses];

export type UpdateProfileData = {
	body: UserDto;
	path?: never;
	query?: never;
	url: "/user/profile";
};

export type UpdateProfileErrors = {
	401: UnauthorizedErrorResponseDto;
	404: NotFoundErrorResponseDto;
	422: UnprocessableEntityErrorResponseDto;
	500: InternalServerErrorResponseDto;
};

export type UpdateProfileError = UpdateProfileErrors[keyof UpdateProfileErrors];

export type UpdateProfileResponses = {
	200: UserUpdateResponseDto;
};

export type UpdateProfileResponse =
	UpdateProfileResponses[keyof UpdateProfileResponses];

export type LoginData = {
	body: AuthDto;
	path?: never;
	query?: never;
	url: "/auth/login";
};

export type LoginErrors = {
	404: NotFoundErrorResponseDto;
	422: UnprocessableEntityErrorResponseDto;
	500: InternalServerErrorResponseDto;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
	200: UserResponseDto;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type RegisterData = {
	body: AuthDto;
	path?: never;
	query?: never;
	url: "/auth/register";
};

export type RegisterErrors = {
	401: UnauthorizedErrorResponseDto;
	404: NotFoundErrorResponseDto;
	422: UnprocessableEntityErrorResponseDto;
	500: InternalServerErrorResponseDto;
	502: BadRequestErrorResponseDto;
};

export type RegisterError = RegisterErrors[keyof RegisterErrors];

export type RegisterResponses = {
	200: UserResponseDto;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type GetNewTokensData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/auth/login/access-token";
};

export type GetNewTokensErrors = {
	401: UnauthorizedErrorResponseDto;
	404: NotFoundErrorResponseDto;
	500: InternalServerErrorResponseDto;
};

export type GetNewTokensError = GetNewTokensErrors[keyof GetNewTokensErrors];

export type GetNewTokensResponses = {
	200: UserResponseDto;
};

export type GetNewTokensResponse =
	GetNewTokensResponses[keyof GetNewTokensResponses];

export type LogoutData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/auth/logout";
};

export type LogoutErrors = {
	404: NotFoundErrorResponseDto;
	500: InternalServerErrorResponseDto;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
	200: boolean;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];
